name: Backend and Frontend Integration Tests

on:
  pull_request:
    branches:
      - develop
      - main
    types:
      - closed

jobs:
  build:
    if: github.event.pull_request.merged == true  # Verifica que el pull request haya sido mergeado
    runs-on: ubuntu-latest

    steps:
    - name: Check out backend code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref_name }}

    - name: Check out frontend repository
      uses: actions/checkout@v3
      with:
        repository: Hexa-bits/Front-End  # Cambia con la ruta completa del repositorio de frontend
        ref: develop    # Uso la rama develop para comprobar
        path: frontend  # Clona el repositorio en una carpeta `frontend`
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install backend dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install frontend dependencies
      run: |
        cd frontend
        npm install

    - name: Run backend tests
      run: pytest

    - name: Run frontend tests
      run: |
        cd frontend
        npx vitest --run